[devshell]
packages = ["mysql80"]

[[commands]]
name = "dev-frontend-vite"
command = "yarn frontend:dev"
help = "Start dev server for frontend code"
category = "frontend-only"

[[commands]]
name = "dev-proxy"
command = "yarn frontend:proxy"
help = "Start proxy to access production from frontend"
category = "frontend-only"

[[commands]]
name = "dev-frontend"
command = "yarn frontend"
help = "Start everything for frontend-only development"
category = "frontend-only"

[[commands]]
name = "dev-frontend-local"
command = "yarn full:frontend"
help = "Start frontend"
category = "fullstack"

[[commands]]
name = "dev-server"
command = "yarn full:server"
help = "Start dev server for backend code"
category = "fullstack"

[[commands]]
name = "dev-db"
command = "yarn full:db"
help = "Start database"
category = "fullstack"

[[commands]]
name = "db-push"
command = "yarn workspace songbook-workers db-push"
help = "Apply changes to database"
category = "fullstack"

[[commands]]
name = "dev"
command = "yarn full"
help = "Start everything needed for fullstack development"
category = "fullstack"
