name = "songbook"
type = "javascript"
account_id = "cce7f3b93d1cc5016fffc6068a30a3bb"
workers_dev = true
route = "zpevnik.skorepova.info/api/*"
zone_id = ""

[build]
command = "yarn && yarn build"

[build.upload]
format = "service-worker"
